import pefile,getpass, datetime,time

name = getpass.getuser()
currenttime = datetime.datetime.now()

file_name = input('Please enter an .exe file name: ')
if file_name.find('.exe') == -1:
    file_name = ''.join(file_name + '.exe')

print('Report generated by:',name)
print('Contact   :', name + '@edu.sait.ca')
print('Date/Time :',currenttime.strftime('%b-%d-%Y %H:%M:%S'),'(utc:',int(time.time()),')')

pe = pefile.PE(file_name)
print()
print('File Name        :',file_name)
print('Magic            :',hex(pe.DOS_HEADER.e_magic).upper().replace('X','x'))
print('PE Header Offset :',hex(pe.DOS_HEADER.e_lfanew).upper().replace('X','x'))
print('Format           :',hex(pe.FILE_HEADER.Machine)[4:] + ' bit')
print('Machine          :',hex(pe.FILE_HEADER.Machine))
print('Entry Point      :',hex(pe.OPTIONAL_HEADER.AddressOfEntryPoint).upper().replace('X','x'))